services:
  voice-assistant:
    build: .
    env_file:
      - .env
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    working_dir: /app
    command: ["python", "main.py"]
    tty: true
